name: 'equitylens'
version: '1.0.0'
config-version: 2

profile: 'stock_research_agent'

model-paths: ["models"]
test-paths: ["tests"]

models:
  stock_research_agent:
    staging:
      +materialized: view
      +schema: ""
    marts:
      +materialized: view
      +schema: ""