"""All agent node functions for the LangGraph workflow.

Nodes:
* DataFetcher        – fetches financials and news for a ticker.
* RAGRetriever       – indexes recent SEC filings into Chroma and retrieves top chunks.
* SentimentAnalyzer  – refines/normalizes news sentiment signals.
* FinancialAnalyzer  – derives a scalar risk score from financials (and optionally news).
* ReportGenerator    – calls Groq (llama-3.1-8b-instant) to produce the final report text.
"""

from __future__ import annotations

import os
from statistics import mean
from typing import Any, List

from src.agents.state import AgentState, RetrievedDoc
from src.data.finance_client import FinanceClientError, fetch_financials
from src.data.sec_client import SECClientError, fetch_filings
from src.rag.embedder import chunk_and_embed
from src.rag.retriever import Retriever
from src.rag.vector_store import vector_store


def _set_error(state: AgentState, message: str) -> AgentState:
    state.error = message
    return state


def data_fetcher_node(state: AgentState) -> AgentState:
    """DataFetcher – populate financials and news for the ticker."""

    if not state.ticker or not state.ticker.strip():
        return _set_error(state, "Ticker is required for data fetching.")

    ticker = state.ticker.strip().upper()

    # Fetch financials.
    try:
        state.financials = fetch_financials(ticker)
    except FinanceClientError as exc:
        return _set_error(state, f"Failed to fetch financials for {ticker}: {exc}")

    # News is generated by SentimentAnalyzer via Groq LLM — skip NewsAPI/yfinance.
    state.news = []

    return state


def rag_retriever_node(state: AgentState) -> AgentState:
    """RAGRetriever – index SEC filings and retrieve relevant chunks via Pinecone."""

    if not state.ticker or not state.ticker.strip():
        return _set_error(state, "Ticker is required for RAG retrieval.")

    ticker = state.ticker.strip().upper()

    if not vector_store.ticker_exists(ticker):
        try:
            filings = fetch_filings(ticker, "10-K", count=3)
        except SECClientError as exc:
            return _set_error(state, f"Failed to fetch SEC filings for {ticker}: {exc}")

        print("Using FinBERT financial embeddings")
        print("Embedding dimension: 768")
        print("Indexing SEC filings into Pinecone...")

        total_chunks = 0
        for filing in filings:
            if not filing.text or not filing.text.strip():
                continue
            chunks = chunk_and_embed(filing.text, ticker)
            if chunks:
                n = vector_store.upsert_chunks(chunks, ticker)
                total_chunks += n
        print(f"Indexed {total_chunks} chunks for {ticker}")
    else:
        print(f"Using cached Pinecone vectors for {ticker}")

    print("Retrieving relevant sections from SEC filing...")

    retriever = Retriever()

    query = (
        "Key risk factors, forward-looking statements, and major business trends "
        "relevant for an investment decision in this company."
    )
    try:
        passages = retriever.search(
            query,
            top_k=10,
            candidate_pool_size=30,
            where={"ticker": ticker},
        )
    except Exception as exc:
        return _set_error(state, f"RAG retrieval failed for {ticker}: {exc}")

    docs: List[RetrievedDoc] = []
    for p in passages:
        docs.append(
            RetrievedDoc(
                id=p.get("id", ""),
                text=p.get("text", ""),
                metadata=p.get("metadata", {}),
                score=p.get("score"),
            )
        )
    state.retrieved_docs = docs
    return state


def sentiment_analyzer_node(state: AgentState) -> AgentState:
    """SentimentAnalyzer – use Groq LLM to analyze market sentiment (ignore NewsAPI/yfinance)."""

    import json
    import os

    import yfinance as yf
    from groq import Groq

    from src.data.normalizer import NewsItem

    ticker = state.ticker or ""
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))

    # Get company name
    try:
        info = yf.Ticker(ticker).info
        company_name = info.get("longName") or ticker
    except Exception:
        company_name = ticker

    # Use LLM to analyze current market sentiment
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "system",
                "content": """You are a financial analyst.
            When given a company name and ticker, analyze
            the general market sentiment based on your
            knowledge. Return a JSON object only,
            no other text.""",
            },
            {
                "role": "user",
                "content": f"""Analyze market sentiment for
            {company_name} ({ticker}).

            Return ONLY this JSON, nothing else:
            {{
                "overall_score": <float between -1 and 1>,
                "label": "<Bullish|Slightly Bullish|Neutral|Slightly Bearish|Bearish>",
                "summary": "<2 sentence summary of current sentiment>",
                "headlines": [
                    {{"title": "<realistic recent news headline>", "sentiment": "<positive|negative|neutral>", "score": <float -1 to 1>}},
                    {{"title": "<realistic recent news headline>", "sentiment": "<positive|negative|neutral>", "score": <float -1 to 1>}},
                    {{"title": "<realistic recent news headline>", "sentiment": "<positive|negative|neutral>", "score": <float -1 to 1>}},
                    {{"title": "<realistic recent news headline>", "sentiment": "<positive|negative|neutral>", "score": <float -1 to 1>}},
                    {{"title": "<realistic recent news headline>", "sentiment": "<positive|negative|neutral>", "score": <float -1 to 1>}}
                ]
            }}""",
            },
        ],
        max_tokens=600,
        temperature=0.3,
    )

    try:
        text = response.choices[0].message.content.strip()
        text = text.replace("```json", "").replace("```", "").strip()
        sentiment_data = json.loads(text)
    except Exception:
        sentiment_data = {
            "overall_score": 0.0,
            "label": "Neutral",
            "summary": f"Market sentiment for {company_name} is currently neutral.",
            "headlines": [],
        }

    # Convert headlines to NewsItem for state
    headlines = sentiment_data.get("headlines", [])
    state.news = [
        NewsItem(
            id=None,
            ticker=ticker,
            tickers=[ticker],
            source_name="AI Analysis",
            author=None,
            title=h.get("title", ""),
            description=h.get("title"),
            url="",
            image_url=None,
            published_at=None,
            content=None,
            sentiment_score=float(h.get("score", 0)),
            sentiment_label=h.get("sentiment", "neutral"),
            relevance_score=None,
        )
        for h in headlines
    ]

    overall = float(sentiment_data.get("overall_score", 0))
    state.sentiment_score = overall
    state.sentiment_label = sentiment_data.get("label", "Neutral")
    state.sentiment_summary = sentiment_data.get("summary", "")
    state.overall_sentiment_score = round(overall, 3)
    return state


def financial_analyzer_node(state: AgentState) -> AgentState:
    """FinancialAnalyzer – derive a scalar risk score from financials and news."""

    if state.financials is None:
        return _set_error(state, "Financials must be present before risk analysis.")

    f = state.financials

    # Start from a neutral baseline.
    risk = 50.0

    # Basic heuristics: stronger margins and positive profit margin lower risk.
    if f.profit_margin is not None:
        if f.profit_margin > 0.2:
            risk -= 10
        elif f.profit_margin < 0.0:
            risk += 10

    if f.revenue is not None and f.revenue <= 0:
        risk += 10

    # Incorporate simple news sentiment (if available).
    sentiment_scores = [n.sentiment_score for n in state.news if n.sentiment_score is not None]
    if sentiment_scores:
        avg_sentiment = mean(sentiment_scores)
        risk -= avg_sentiment * 10.0

    risk = max(0.0, min(100.0, risk))
    state.risk_score = risk
    return state


def calculate_recommendation(
    financials: dict | None,
    sentiment_score: float,
) -> tuple[str, int, list[str]]:
    """Compute BUY/HOLD/SELL and reasons from financials and sentiment."""
    score = 0
    reasons: List[str] = []

    f = financials or {}

    # P/E Ratio
    pe = f.get("pe_ratio") or f.get("trailing_pe")
    if pe is not None:
        pe_val = float(pe)
        if pe_val < 15:
            score += 2
            reasons.append("Low P/E ratio suggests stock is undervalued")
        elif pe_val < 25:
            score += 1
            reasons.append("P/E ratio is reasonable")
        elif pe_val > 40:
            score -= 2
            reasons.append("High P/E ratio — stock may be overvalued")

    # Profit margin
    margin = f.get("profit_margin")
    if margin is not None:
        m = float(margin)
        if m > 0.20:
            score += 2
            reasons.append(f"Strong profit margin of {m * 100:.1f}%")
        elif m > 0.10:
            score += 1
            reasons.append(f"Decent profit margin of {m * 100:.1f}%")
        elif m < 0:
            score -= 2
            reasons.append("Company is losing money")

    # Revenue
    revenue = f.get("revenue")
    if revenue is not None and float(revenue) > 100_000_000_000:
        score += 1
        reasons.append("Large established company with massive revenue")

    # Sentiment
    if sentiment_score > 0.3:
        score += 2
        reasons.append("Very positive news sentiment")
    elif sentiment_score > 0.1:
        score += 1
        reasons.append("Slightly positive news")
    elif sentiment_score < -0.3:
        score -= 2
        reasons.append("Very negative news sentiment")
    elif sentiment_score < -0.1:
        score -= 1
        reasons.append("Slightly negative news")

    if score >= 3:
        return "BUY", score, reasons
    if score <= -2:
        return "SELL", score, reasons
    return "HOLD", score, reasons


def _get_groq_client() -> Any:
    """Create Groq client. Import inside to avoid circular imports."""
    from groq import Client as GroqClient

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY is not set. Obtain a key from console.groq.com and add it to your .env file."
        )
    return GroqClient(api_key=api_key)


def report_generator_node(state: AgentState) -> AgentState:
    """ReportGenerator – compute BUY/HOLD/SELL from financials and sentiment, generate plain-English summary."""

    if not state.ticker:
        return _set_error(state, "Ticker is required to generate a report.")

    ticker = state.ticker.strip().upper()
    financials = state.financials
    news = state.news or []

    if financials is None:
        return _set_error(state, "Financials must be present to generate a report.")

    # Calculate sentiment score from news
    if news:
        scores = [getattr(n, "sentiment_score", None) or 0 for n in news]
        sentiment_avg = sum(scores) / len(scores)
    else:
        sentiment_avg = 0.0

    pe = financials.pe_ratio or 0
    margin = financials.profit_margin or 0
    eps = financials.eps or 0
    revenue = financials.revenue or 0
    price = financials.current_price or 0

    score = 0
    reasons: List[str] = []

    # P/E Analysis
    if 0 < pe < 15:
        score += 3
        reasons.append(f"Very attractive P/E of {pe:.1f} — stock looks undervalued")
    elif 15 <= pe < 25:
        score += 1
        reasons.append(f"Reasonable P/E of {pe:.1f} — fairly valued")
    elif 25 <= pe < 40:
        score -= 1
        reasons.append(f"Elevated P/E of {pe:.1f} — slightly expensive")
    elif pe >= 40:
        score -= 3
        reasons.append(f"Very high P/E of {pe:.1f} — stock looks overvalued")

    # Profit Margin Analysis
    if margin > 0.25:
        score += 3
        reasons.append(f"Exceptional profit margin of {margin * 100:.1f}%")
    elif margin > 0.15:
        score += 2
        reasons.append(f"Strong profit margin of {margin * 100:.1f}%")
    elif margin > 0.05:
        score += 1
        reasons.append(f"Decent profit margin of {margin * 100:.1f}%")
    elif margin < 0:
        score -= 3
        reasons.append(f"Company is currently losing money (margin: {margin * 100:.1f}%)")

    # EPS Analysis
    if eps > 10:
        score += 2
        reasons.append(f"High earnings per share of ${eps:.2f}")
    elif eps > 3:
        score += 1
        reasons.append(f"Solid earnings per share of ${eps:.2f}")
    elif eps < 0:
        score -= 2
        reasons.append(f"Negative earnings — company losing ${abs(eps):.2f} per share")

    # Sentiment Analysis
    if sentiment_avg > 0.3:
        score += 2
        reasons.append("Very positive news coverage")
    elif sentiment_avg > 0.1:
        score += 1
        reasons.append("Generally positive news sentiment")
    elif sentiment_avg < -0.3:
        score -= 2
        reasons.append("Very negative news coverage")
    elif sentiment_avg < -0.1:
        score -= 1
        reasons.append("Negative news sentiment")

    # Final recommendation
    if score >= 4:
        recommendation = "BUY"
        risk_score_val = max(20.0, 50 - score * 5)
        verdict_color = "green"
    elif score <= -3:
        recommendation = "SELL"
        risk_score_val = min(85.0, 50 + abs(score) * 5)
        verdict_color = "red"
    else:
        recommendation = "HOLD"
        risk_score_val = 50.0
        verdict_color = "amber"

    state.recommendation = recommendation
    state.recommendation_score = score
    state.recommendation_reasons = reasons
    state.risk_score = risk_score_val
    state.overall_sentiment_score = round(sentiment_avg, 3)
    # Do not overwrite sentiment_label, sentiment_score, sentiment_summary – they come from SentimentAnalyzer LLM.

    # Fetch company name for LLM prompt
    from src.data.finance_client import fetch_company_profile

    profile = fetch_company_profile(ticker)
    company_name = profile.get("longName") or profile.get("shortName") or ticker

    # Generate plain English summary via Groq
    try:
        client = _get_groq_client()
    except RuntimeError as exc:
        return _set_error(state, str(exc))

    margin_pct = f"{margin * 100:.1f}%" if margin is not None else "N/A"
    prompt = f"""You are explaining a stock to someone who has never invested before. Be conversational and clear. No jargon.

Company: {company_name}
Price: ${price:.2f}
P/E Ratio: {pe}
Profit Margin: {margin_pct}
EPS: ${eps:.2f}
Recommendation: {recommendation}
Score: {score}

Write exactly 4 short sentences:
1. What this company does (very simple)
2. How their finances look right now
3. Our recommendation and why in simple terms
4. One risk to be aware of

Sound like a smart friend explaining, not a robot."""

    try:
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.3,
        )
        content = response.choices[0].message.content
        if content:
            state.plain_english_summary = content.strip()
    except Exception as exc:
        return _set_error(state, f"Groq API call failed: {exc}")

    # Generate bull/bear cases and 12-month price target
    import json

    try:
        bull_bear_response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {
                    "role": "user",
                    "content": f"""You are a Wall Street analyst.
For {company_name} ({ticker}) with current price ${price:.2f}, P/E {pe}, margin {margin * 100:.1f}%,
recommendation {recommendation}:

Return ONLY this JSON, no other text:
{{
    "price_target": <realistic 12-month price target as number>,
    "price_target_upside": <% upside/downside from current price>,
    "bull_case": "<2 sentences: best case scenario for this stock>",
    "bear_case": "<2 sentences: worst case scenario for this stock>",
    "time_horizon": "12 months"
}}""",
                }
            ],
            max_tokens=200,
            temperature=0.3,
        )
        text = bull_bear_response.choices[0].message.content or ""
        text = text.replace("```json", "").replace("```", "").strip()
        bull_bear = json.loads(text)
    except Exception:
        bull_bear = {
            "price_target": round(price * 1.1, 2),
            "price_target_upside": 10.0,
            "bull_case": "Strong fundamentals and market position could drive significant upside.",
            "bear_case": "Macro headwinds and competition could pressure margins and growth.",
            "time_horizon": "12 months",
        }

    state.price_target = bull_bear.get("price_target")
    state.price_target_upside = bull_bear.get("price_target_upside")
    state.bull_case = bull_bear.get("bull_case")
    state.bear_case = bull_bear.get("bear_case")
    state.time_horizon = bull_bear.get("time_horizon", "12 months")

    financial_health = (
        f"Revenue ${revenue:,.0f}, EPS ${eps:.2f}, margin {margin_pct}, P/E {pe:.1f}."
    )

    plain_summary = state.plain_english_summary or ""
    risk_score = risk_score_val

    state.report = {
        "recommendation": recommendation,
        "risk_score": int(risk_score),
        "score": int(score),
        "reasons": reasons[:5],
        "financial_health": financial_health,
        "plain_summary": plain_summary,
        "price_target": float(bull_bear.get("price_target", float(price) * 1.1)),
        "price_target_upside": float(bull_bear.get("price_target_upside", 10.0)),
        "bull_case": str(
            bull_bear.get(
                "bull_case", "Strong market position could drive upside."
            )
        ),
        "bear_case": str(
            bull_bear.get(
                "bear_case", "Market headwinds could pressure growth."
            )
        ),
        "time_horizon": "12 months",
    }
    return state

